"""Domain enumerations — enforced across schemas and validation."""

from enum import StrEnum


class SourceMode(StrEnum):
    LIVE = "LIVE"
    SIMULATED = "SIMULATED"
    SYNTHETIC = "SYNTHETIC"
    MOCKED = "MOCKED"
    USER_PROVIDED = "USER_PROVIDED"


class EvidenceType(StrEnum):
    RESUME = "RESUME"
    PORTFOLIO = "PORTFOLIO"
    PROJECT = "PROJECT"
    CERTIFICATION = "CERTIFICATION"
    WORK_HISTORY = "WORK_HISTORY"
    ASSESSMENT = "ASSESSMENT"
    SELF_REPORTED = "SELF_REPORTED"
    SAP_PROFILE = "SAP_PROFILE"
    SAP_SKILL = "SAP_SKILL"
    SAP_LEARNING = "SAP_LEARNING"
    OTHER = "OTHER"


class VerificationStatus(StrEnum):
    """SELF_REPORTED evidence must not be VERIFIED without corroboration."""

    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    SELF_REPORTED = "SELF_REPORTED"


class InferenceStatus(StrEnum):
    EXPLICIT = "EXPLICIT"
    INFERRED = "INFERRED"
    TRANSFERABLE = "TRANSFERABLE"
    ADJACENT = "ADJACENT"
    VERIFIED = "VERIFIED"


class GapStatus(StrEnum):
    """Diagnosis classification for capability/requirement comparison."""

    MATCHED = "MATCHED"
    GENUINE_CAPABILITY_GAP = "GENUINE_CAPABILITY_GAP"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ELIGIBILITY_PROXY = "ELIGIBILITY_PROXY"
    WORKPLACE_CONSTRAINT = "WORKPLACE_CONSTRAINT"
    UNKNOWN_REQUIRES_HUMAN_REVIEW = "UNKNOWN_REQUIRES_HUMAN_REVIEW"


# Alias used in diagnosis APIs — same values as GapStatus.
DiagnosisType = GapStatus


class BarrierType(StrEnum):
    NONE = "NONE"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    WORKPLACE_CONSTRAINT = "WORKPLACE_CONSTRAINT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNKNOWN = "UNKNOWN"


class OverallDiagnosisState(StrEnum):
    """Structured diagnosis summary — not a hiring decision."""

    STRONG_MATCH = "STRONG_MATCH"
    MATCH_WITH_GAPS = "MATCH_WITH_GAPS"
    POTENTIALLY_VIABLE = "POTENTIALLY_VIABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    NOT_CURRENTLY_READY = "NOT_CURRENTLY_READY"


class RequirementClass(StrEnum):
    DIRECT_CAPABILITY = "DIRECT_CAPABILITY"
    EVIDENCE_REQUIREMENT = "EVIDENCE_REQUIREMENT"
    CREDENTIAL_REQUIREMENT = "CREDENTIAL_REQUIREMENT"
    EXPERIENCE_REQUIREMENT = "EXPERIENCE_REQUIREMENT"
    WORKPLACE_CONDITION = "WORKPLACE_CONDITION"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    UNKNOWN = "UNKNOWN"


class ReviewTag(StrEnum):
    NONE = "NONE"
    POTENTIAL_EXCLUSIONARY_FACTOR = "POTENTIAL_EXCLUSIONARY_FACTOR"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class CounterfactualConclusion(StrEnum):
    REQUIREMENT_APPEARS_JOB_RELEVANT = "REQUIREMENT_APPEARS_JOB_RELEVANT"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class RecommendationState(StrEnum):
    MATCHED = "MATCHED"
    PATHWAY_RECOMMENDED = "PATHWAY_RECOMMENDED"
    PROOF_REQUIRED = "PROOF_REQUIRED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    NOT_CURRENTLY_READY = "NOT_CURRENTLY_READY"


class ReadinessState(StrEnum):
    READY_NOW = "ready_now"
    READY_WITH_PROOF = "ready_with_proof"
    READY_WITH_BOUNDED_PATHWAY = "ready_with_bounded_pathway"
    NOT_READY = "not_ready"


class HumanReviewAction(StrEnum):
    APPROVE = "APPROVE"
    MODIFY = "MODIFY"
    REJECT = "REJECT"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"
    DEFER = "DEFER"


class AuditStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    SKIPPED = "SKIPPED"


class IntegrationStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    DEGRADED = "DEGRADED"


class EngineMode(StrEnum):
    LLM = "LLM"
    DEMO_FALLBACK = "DEMO_FALLBACK"


class RecencyStatus(StrEnum):
    RECENT = "RECENT"
    AGING = "AGING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class CapabilityVerificationStatus(StrEnum):
    """Capability-level verification derived from evidence."""

    SELF_REPORTED = "SELF_REPORTED"
    UNVERIFIED = "UNVERIFIED"
    SUPPORTED = "SUPPORTED"
    VERIFIED = "VERIFIED"
