"""Domain enumerations — enforced across schemas and validation."""

from enum import StrEnum


class SourceMode(StrEnum):
    LIVE = "LIVE"
    SIMULATED = "SIMULATED"
    NOT_CONNECTED = "NOT_CONNECTED"
    ERROR = "ERROR"
    SYNTHETIC = "SYNTHETIC"
    MOCKED = "MOCKED"
    USER_PROVIDED = "USER_PROVIDED"


class EvidenceType(StrEnum):
    RESUME = "RESUME"
    PORTFOLIO = "PORTFOLIO"
    PROJECT = "PROJECT"
    CERTIFICATION = "CERTIFICATION"
    WORK_HISTORY = "WORK_HISTORY"
    ASSESSMENT = "ASSESSMENT"
    SELF_REPORTED = "SELF_REPORTED"
    SAP_PROFILE = "SAP_PROFILE"
    SAP_SKILL = "SAP_SKILL"
    SAP_LEARNING = "SAP_LEARNING"
    OTHER = "OTHER"


class VerificationStatus(StrEnum):
    """SELF_REPORTED evidence must not be VERIFIED without corroboration."""

    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    SELF_REPORTED = "SELF_REPORTED"


class InferenceStatus(StrEnum):
    EXPLICIT = "EXPLICIT"
    INFERRED = "INFERRED"
    TRANSFERABLE = "TRANSFERABLE"
    ADJACENT = "ADJACENT"
    VERIFIED = "VERIFIED"


class GapStatus(StrEnum):
    """Diagnosis classification for capability/requirement comparison."""

    MATCHED = "MATCHED"
    GENUINE_CAPABILITY_GAP = "GENUINE_CAPABILITY_GAP"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ELIGIBILITY_PROXY = "ELIGIBILITY_PROXY"
    WORKPLACE_CONSTRAINT = "WORKPLACE_CONSTRAINT"
    UNKNOWN_REQUIRES_HUMAN_REVIEW = "UNKNOWN_REQUIRES_HUMAN_REVIEW"


# Alias used in diagnosis APIs — same values as GapStatus.
DiagnosisType = GapStatus


class BarrierType(StrEnum):
    NONE = "NONE"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    WORKPLACE_CONSTRAINT = "WORKPLACE_CONSTRAINT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNKNOWN = "UNKNOWN"


class OverallDiagnosisState(StrEnum):
    """Structured diagnosis summary — not a hiring decision."""

    STRONG_MATCH = "STRONG_MATCH"
    MATCH_WITH_GAPS = "MATCH_WITH_GAPS"
    POTENTIALLY_VIABLE = "POTENTIALLY_VIABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    NOT_CURRENTLY_READY = "NOT_CURRENTLY_READY"


class RequirementClass(StrEnum):
    DIRECT_CAPABILITY = "DIRECT_CAPABILITY"
    EVIDENCE_REQUIREMENT = "EVIDENCE_REQUIREMENT"
    CREDENTIAL_REQUIREMENT = "CREDENTIAL_REQUIREMENT"
    EXPERIENCE_REQUIREMENT = "EXPERIENCE_REQUIREMENT"
    WORKPLACE_CONDITION = "WORKPLACE_CONDITION"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    UNKNOWN = "UNKNOWN"


class ReviewTag(StrEnum):
    NONE = "NONE"
    POTENTIAL_EXCLUSIONARY_FACTOR = "POTENTIAL_EXCLUSIONARY_FACTOR"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class CounterfactualConclusion(StrEnum):
    REQUIREMENT_APPEARS_JOB_RELEVANT = "REQUIREMENT_APPEARS_JOB_RELEVANT"
    POTENTIAL_PROXY = "POTENTIAL_PROXY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class RecommendationState(StrEnum):
    MATCHED = "MATCHED"
    PATHWAY_RECOMMENDED = "PATHWAY_RECOMMENDED"
    PROOF_REQUIRED = "PROOF_REQUIRED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    NOT_CURRENTLY_READY = "NOT_CURRENTLY_READY"


class ReadinessState(StrEnum):
    READY_NOW = "ready_now"
    READY_WITH_PROOF = "ready_with_proof"
    READY_WITH_BOUNDED_PATHWAY = "ready_with_bounded_pathway"
    NOT_READY = "not_ready"


class HumanReviewAction(StrEnum):
    APPROVE = "APPROVE"
    MODIFY = "MODIFY"
    REJECT = "REJECT"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"
    DEFER = "DEFER"


class AuditStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    SKIPPED = "SKIPPED"


class IntegrationStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    DEGRADED = "DEGRADED"


class EngineMode(StrEnum):
    LLM = "LLM"
    DEMO_FALLBACK = "DEMO_FALLBACK"


class RecencyStatus(StrEnum):
    RECENT = "RECENT"
    AGING = "AGING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class CapabilityVerificationStatus(StrEnum):
    """Capability-level verification derived from evidence."""

    SELF_REPORTED = "SELF_REPORTED"
    UNVERIFIED = "UNVERIFIED"
    SUPPORTED = "SUPPORTED"
    VERIFIED = "VERIFIED"
    VERIFIED_BY_ASSESSMENT = "VERIFIED_BY_ASSESSMENT"


class PathwayStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    IN_PROGRESS = "IN_PROGRESS"
    READY_FOR_PROOF = "READY_FOR_PROOF"
    PROOF_SUBMITTED = "PROOF_SUBMITTED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    PROOF_FAILED = "PROOF_FAILED"


class MilestoneStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"


class RunMode(StrEnum):
    ANALYZE_ONLY = "ANALYZE_ONLY"
    GENERATE_PATHWAY = "GENERATE_PATHWAY"
    EVALUATE_PROOF = "EVALUATE_PROOF"
    FULL_DEMO_REPLAY = "FULL_DEMO_REPLAY"
    OPPORTUNITY_ANALYSIS = "OPPORTUNITY_ANALYSIS"
    CONTROL_ROOM_DEMO = "CONTROL_ROOM_DEMO"


class InterventionType(StrEnum):
    LEARNING = "LEARNING"
    PROOF_OF_SKILL = "PROOF_OF_SKILL"
    MENTORSHIP = "MENTORSHIP"
    PHASED_RESPONSIBILITY = "PHASED_RESPONSIBILITY"
    HYBRID_WORK = "HYBRID_WORK"
    REMOTE_WORK = "REMOTE_WORK"
    FLEXIBLE_SCHEDULE = "FLEXIBLE_SCHEDULE"
    STRUCTURED_ONBOARDING = "STRUCTURED_ONBOARDING"
    WORKPLACE_ACCOMMODATION = "WORKPLACE_ACCOMMODATION"
    TASK_REDESIGN = "TASK_REDESIGN"
    EVIDENCE_SUBSTITUTION = "EVIDENCE_SUBSTITUTION"
    MANAGER_SUPPORT = "MANAGER_SUPPORT"


class InterventionPriority(StrEnum):
    HIGH_IMPACT_LOW_EFFORT = "HIGH_IMPACT_LOW_EFFORT"
    HIGH_IMPACT_HIGH_EFFORT = "HIGH_IMPACT_HIGH_EFFORT"
    LOW_IMPACT_LOW_EFFORT = "LOW_IMPACT_LOW_EFFORT"
    LOW_IMPACT_HIGH_EFFORT = "LOW_IMPACT_HIGH_EFFORT"
    UNKNOWN = "UNKNOWN"


class ConfidenceLabel(StrEnum):
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNCERTAIN = "UNCERTAIN"


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    AI = "AI"
    HUMAN = "HUMAN"


class CaseLifecycleState(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    DISCOVERED = "DISCOVERED"
    DECOMPOSED = "DECOMPOSED"
    DIAGNOSED = "DIAGNOSED"
    COUNTERFACTUAL_ANALYZED = "COUNTERFACTUAL_ANALYZED"
    PATHWAY_GENERATED = "PATHWAY_GENERATED"
    PROOF_PENDING = "PROOF_PENDING"
    PROOF_COMPLETED = "PROOF_COMPLETED"
    REASSESSED = "REASSESSED"
    MARKET_ANALYZED = "MARKET_ANALYZED"
    OPPORTUNITIES_EVALUATED = "OPPORTUNITIES_EVALUATED"
    INTERVENTIONS_SIMULATED = "INTERVENTIONS_SIMULATED"
    EXPLANATION_READY = "EXPLANATION_READY"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    DECISION_RECORDED = "DECISION_RECORDED"
    OUTCOME_PENDING = "OUTCOME_PENDING"
    OUTCOME_RECORDED = "OUTCOME_RECORDED"
    EVIDENCE_PENDING = "EVIDENCE_PENDING"
    CLOSED = "CLOSED"


class CaseStage(StrEnum):
    """Execution stage targets for partial case runs."""

    DISCOVERY = "DISCOVERY"
    DECOMPOSITION = "DECOMPOSITION"
    DIAGNOSIS = "DIAGNOSIS"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    PATHWAY_GENERATION = "PATHWAY_GENERATION"
    PROOF_EVALUATION = "PROOF_EVALUATION"
    REASSESSMENT = "REASSESSMENT"
    MARKET_INTELLIGENCE = "MARKET_INTELLIGENCE"
    OPPORTUNITY_VIABILITY = "OPPORTUNITY_VIABILITY"
    INTERVENTION_SIMULATION = "INTERVENTION_SIMULATION"
    EXPLAINABILITY = "EXPLAINABILITY"
    FINALE = "FINALE"


class CaseEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CANDIDATE_DISCOVERED = "CANDIDATE_DISCOVERED"
    JOB_DECOMPOSED = "JOB_DECOMPOSED"
    DIAGNOSIS_CREATED = "DIAGNOSIS_CREATED"
    COUNTERFACTUAL_CREATED = "COUNTERFACTUAL_CREATED"
    PATHWAY_GENERATED = "PATHWAY_GENERATED"
    PROOF_SUBMITTED = "PROOF_SUBMITTED"
    CAPABILITY_UPDATED = "CAPABILITY_UPDATED"
    REASSESSMENT_COMPLETED = "REASSESSMENT_COMPLETED"
    MARKET_ANALYZED = "MARKET_ANALYZED"
    OPPORTUNITY_EVALUATED = "OPPORTUNITY_EVALUATED"
    INTERVENTION_SIMULATED = "INTERVENTION_SIMULATED"
    EXPLANATION_GENERATED = "EXPLANATION_GENERATED"
    HUMAN_DECISION_RECORDED = "HUMAN_DECISION_RECORDED"
    CASE_EXECUTED = "CASE_EXECUTED"
    SNAPSHOT_STORED = "SNAPSHOT_STORED"


class InterventionScenarioType(StrEnum):
    BASELINE = "BASELINE"
    LEARNING_ONLY = "LEARNING_ONLY"
    PROOF_ONLY = "PROOF_ONLY"
    EMPLOYER_ADAPTATION = "EMPLOYER_ADAPTATION"
    LEARNING_PLUS_PROOF = "LEARNING_PLUS_PROOF"
    LEARNING_PLUS_EMPLOYER = "LEARNING_PLUS_EMPLOYER"
    FULL_MINIMUM_EFFECTIVE_INTERVENTION = "FULL_MINIMUM_EFFECTIVE_INTERVENTION"


class HumanDecisionStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"


class ViabilityState(StrEnum):
    IMMEDIATELY_VIABLE = "IMMEDIATELY_VIABLE"
    VIABLE_WITH_TARGETED_PATHWAY = "VIABLE_WITH_TARGETED_PATHWAY"
    VIABLE_WITH_EMPLOYER_ADAPTATION = "VIABLE_WITH_EMPLOYER_ADAPTATION"
    VIABLE_WITH_PATHWAY_AND_ADAPTATION = "VIABLE_WITH_PATHWAY_AND_ADAPTATION"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NOT_CURRENTLY_VIABLE = "NOT_CURRENTLY_VIABLE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class ProofResultStatus(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    PENDING = "PENDING"
